name: JMeter Performance Test

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  perf-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JMeter
      uses: justb4/jmeter-action@v2
      with:
        version: '5.6.3'

    - name: Run JMeter Test
      run: |
        jmeter -n -t BlazeMeter.jmx -l result.jtl -e -o reports/html

    - name: Upload JTL file
      uses: actions/upload-artifact@v4
      with:
        name: result-jtl
        path: result.jtl

    - name: Upload HTML report
      uses: actions/upload-artifact@v4
      with:
        name: html-report
        path: reports/html
